[build-system]
requires = ["setuptools>=77", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "enterprise-data-api"
version = "0.1.0"
requires-python = ">=3.13"

[project.optional-dependencies]
dev = [
  "pytest"
]

dependencies = [
  "FastAPI[standard]",
  "psycopg[binary]",
  "alembic",
  "python-dotenv"
]

[tool.setuptools.packages.find]
include = ["app*"]
exclude = ["alembic*"]